FROM anibali/pytorch:1.5.0-cuda10.2
USER root

WORKDIR /tmp/smp/

COPY ./requirements.txt /tmp/smp/requirements.txt
RUN pip install -r requirements.txt
RUN pip install pytest mock

COPY . /tmp/smp/
RUN pip install .
RUN pip install jupyter lab
RUN pip install jupyter notebook
RUN pip install segmentation-models-pytorch
RUN pip install pytorch-lightning==1.5.4
RUN pip install opencv-python
RUN pip install tensorflow-gpu

WORKDIR /home/test
